export const sections = [
  {
    id: 'all',
    label: 'All Projects',
    description:
      "Here's a little bit of everything.  Some are pretty random... some are *really* old (#NoRegerts). For my web projects, so many of these either no longer exist, or have been redeveloped since I launched them. Archived links *might* be available upon request.",
  },
  {
    id: 'web-dev',
    label: 'Web Development',
    description:
      'Here are some of my more recent web projects. Unfortunately, the web is an ever-evolving beast, so many of these either no longer exist, or have been redeveloped since I launched them. Archived links *might* be available upon request.',
  },
  {
    id: 'music',
    label: 'Music',
    description:
      'In fourth grade, music grabbed me by the ear and never let go. Until I discovered web development, it was my primary passion. Here are a few of the highlights over the years.',
  },
  {
    id: 'photo',
    label: 'Photography',
    description:
      "Along the way, I wound up picking up a camera and found that I kinda liked shooting photos as well. It's never really been a *passion* per se, but it's fun when I have the time.  Enjoy!",
  },
  {
    id: 'misc',
    label: 'Other Stuff',
    description: "Here are some other random things I've done.",
  },
]

export const projects = [
  {
    id: 'mizzen',
    title: 'Mizzen+Main',
    client: 'Mizzen+Main',
    year: '2016-2023',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Mizzen+Main',
    logo: '/images/work/logos/mizzen-logo.png',
    screenshot: '/images/work/screenshots/mizzen-screenshot.jpg',
    url: '',
    media: '/images/work/video/mizzen-walkthrough.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML/CSS/JS', 'Next.js/React', 'Liquid', 'Site Management'],
    notes: 'Notes will go here.',
  },
  {
    id: 'the-release',
    title: 'The Release',
    client: 'The Beta Release (Boots)',
    year: '2021',
    projectType: 'Song',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/thebetarelease-logo.png',
    screenshot: '/images/work/screenshots/thebetarelease-screenshot.jpg',
    url: 'https://thebetarelease.com',
    media:
      'https://soundcloud.com/the-beta-release/the-release?in=the-beta-release/sets/first-four-demo/s-GJmPNOdFLgZ&si=3532862927724aefafb5105e8ec32838&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    mediaType: 'audio',
    skills: ['Writing/Arranging/Production', 'Bass Guitar', 'Guitar', 'Synths', 'Drum Programming'],
    notes: 'Notes will go here.',
  },
  {
    id: 'vale',
    title: 'Vale Counseling',
    client: 'Vale Counseling',
    year: '2017',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/vale-logo.png',
    screenshot: '/images/work/screenshots/vale-screenshot.jpg',
    url: 'http://valecounseling.com',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'adopted',
    title: 'AdoptED',
    client: 'Gladney Center for Adoption',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/adopted-logo.png',
    screenshot: '/images/work/screenshots/adopted-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'ExpressionEngine'],
    notes: 'Notes will go here.',
  },
  {
    id: 'tots-nuggs',
    title: 'Tots & Nuggs',
    client: 'Boots',
    year: '2022',
    projectType: 'Song',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/totsandnuggs-screenshot.jpg',
    url: '',
    media:
      'https://soundcloud.com/the-beta-release/tots-nugs?si=ac1f0deed53e4c989695d00be8cad362&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    mediaType: 'audio',
    skills: ['Writing/Arranging/Production', 'Bass Guitar', 'Guitar', 'Synths', 'Drum Programming'],
    notes: 'Notes will go here.',
  },
  {
    id: 'criquet',
    title: 'Criquet Shirts',
    client: 'Criquet Shirts',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/criquet-logo.png',
    screenshot: '/images/work/screenshots/criquet-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'Shopify'],
    notes: 'Notes will go here.',
  },
  {
    id: 'the-interrogation',
    title: 'The Interrogation',
    client: 'Boots',
    year: '2022',
    projectType: 'Video',
    category: 'misc',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/theinterrogation-screenshot.jpg',
    url: '',
    media: 'https://youtu.be/lhPjK90urgk',
    mediaType: 'video',
    skills: ['Screenplay/Direction/Cinematography', 'Video Editing', 'Acting?'],
    notes: 'Notes will go here.',
  },
  {
    id: 'jordan',
    title: 'Jordan Tourism Board',
    client: 'Jordan Tourism Board North America',
    year: '2005',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/jordan-logo.png',
    screenshot: '/images/work/screenshots/jordan-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'Flash Programming', 'Website Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'the-laurel',
    title: 'The Laurel',
    client: 'The Laurel Texas',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/thelaurel-logo.png',
    screenshot: '/images/work/screenshots/thelaurel-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'gladney',
    title: 'Gladney Center',
    client: 'Gladney Center for Adoption',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/gladney-logo.png',
    screenshot: '/images/work/screenshots/gladney-screenshot.jpg',
    url: 'https://adoptionsbygladney.com/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'dock-bass-solo',
    title: 'Bass Solo @ The Dock',
    client: 'Boots',
    year: '1998',
    projectType: 'Video',
    category: 'music',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/basssolodock-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=Bys69-mxu6E',
    mediaType: 'video',
    skills: ['Bass Guitar'],
    notes: 'Notes will go here.',
  },
  {
    id: 'falchi',
    title: 'The Falchi Building',
    client: 'Jametown Urban Management',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/falchi-logo.png',
    screenshot: '/images/work/screenshots/falchi-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'birds-of-play',
    title: 'Birds of Play',
    client: 'Birds of Play FC',
    year: '2017',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/birdsofplay-logo.png',
    screenshot: '/images/work/screenshots/birdsofplay-screenshot.jpg',
    url: 'http://birdsofplay.boots.media/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'bluebird',
    title: 'Bluebird Real Estate',
    client: 'Bluebird Real Estate',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/bluebird-logo.png',
    screenshot: '/images/work/screenshots/bluebird-screenshot.jpg',
    url: 'https://bbre1.com/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'see-you-today',
    title: 'See You Today',
    client: 'Interface',
    year: '1990',
    projectType: 'Music Video',
    category: 'music',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/seeyoutoday-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=trqFaoDmofs',
    mediaType: 'video',
    skills: ['Bass Guitar'],
    notes: 'Notes will go here.',
  },
  {
    id: 'dallas-guitar-repair',
    title: 'Dallas Guitar Repair',
    client: 'Dallas Guitar Repair',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/dallasguitarrepair-logo.png',
    screenshot: '/images/work/screenshots/dallasguitarrepair-screenshot.jpg',
    url: 'http://dallasguitarrepair.boots.media/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'pregnancy-hotline',
    title: 'Pregnancy Hotline',
    client: 'Gladney Center for Adoption',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/gladney-logo.png',
    screenshot: '/images/work/screenshots/pregnancyhotline-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'ExpressionEngine'],
    notes: 'Notes will go here.',
  },
  {
    id: 'new-years-day',
    title: 'New Years Day',
    client: 'Blood Red Sky',
    year: '2006',
    projectType: 'Music Video',
    category: 'music',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/newyearsday-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=0w_aBtBo7PI',
    mediaType: 'video',
    skills: ['Bass Guitar', 'Video Production'],
    notes: 'Notes will go here.',
  },
  {
    id: 'doubler',
    title: 'Double R',
    client: 'Double R Brand by Ravi Ratan',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/doubler-logo.png',
    screenshot: '/images/work/screenshots/doubler-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'Shopify'],
    notes: 'Notes will go here.',
  },
]
