export const sections = [
  {
    id: 'all',
    label: 'All Projects',
    description:
      "Here's a little bit of everything.  Some are pretty random... some are *really* old (#NoRegerts). For my web projects, so many of these either no longer exist, or have been redeveloped since I launched them. Archived links *might* be available upon request.",
    seo: "Here is a few of the various projects I've had over the years - websites, music, goofy videos, etc.",
  },
  {
    id: 'web-dev',
    label: 'Web Development',
    description:
      'Here are some of my more recent web projects. Unfortunately, the web is an ever-evolving beast, so many of these either no longer exist, or have been redeveloped since I launched them. Archived links *might* be available upon request.',
    seo: 'These are some of my most recent web development projects.',
  },
  {
    id: 'music',
    label: 'Music',
    description:
      'In fourth grade, music grabbed me by the ear and never let go. Until I discovered web development, it was my primary passion. Here are a few of the highlights over the years.',
    seo: "Music was my first passion, and I've had a TON of musical ventures along the way.  Here are some of the highlights.",
  },
  // {
  //   id: 'photo',
  //   label: 'Photography',
  //   description:
  //     "Along the way, I wound up picking up a camera and found that I kinda liked shooting photos as well. It's never really been a *passion* per se, but it's fun when I have the time.  Enjoy!",
  // },
  {
    id: 'misc',
    label: 'Other Stuff',
    description: "Here are some other random things I've done.",
    seo: "Here are some other random things I've done.",
  },
]

export const projects = [
  {
    id: 'mizzen',
    title: 'Mizzen+Main',
    client: 'Mizzen+Main',
    year: '2016-2023',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Mizzen+Main',
    logo: '/images/work/logos/mizzen-logo.png',
    screenshot: '/images/work/screenshots/mizzen-screenshot.jpg',
    url: '',
    media: '/images/work/video/mizzen-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML/CSS/JS', 'Next.js/React', 'Liquid', 'Site Management'],
    notes:
      '<p>After 20+ years building websites for clients, my time with Mizzen+Main was my first chance to have my own "baby". I was the Sr Manager of Web Development for Mizzen+Main, which meant I was in charge of everything to do with the website.  I handled 90% of the front-end development for the site, and managed a team of developers for the rest. Mizzen is a Shopify store, and when I started, we were on the older Liquid platform.</p>\
      <p>In 2022, I was able to lead our team through transitioning to a more modern "headless" site, using React/Next.js and Sanity CMS, while pulling in product data through the Shopify APIs. This is a massive site, and performed extremely well as the company grew. I\'m SUPER proud of the work I was able to do at Mizzen.</p>\
      <p>Since I\'ve left, the site has gone through some significant changes, so unfortunately I can only show a video of the site from my time there.</p>',
  },
  {
    id: 'the-release',
    title: 'The Release',
    client: 'The Beta Release (AKA Boots)',
    year: '2021',
    projectType: 'Song',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/thebetarelease-logo.png',
    screenshot: '/images/work/screenshots/thebetarelease2-screenshot.jpg',
    url: '',
    media:
      'https://soundcloud.com/the-beta-release/the-release?in=the-beta-release/sets/first-four-demo/s-GJmPNOdFLgZ&si=3532862927724aefafb5105e8ec32838&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    mediaType: 'audio',
    skills: ['Writing/Arranging/Production', 'Bass Guitar', 'Guitar', 'Synths', 'Drum Programming'],
    notes:
      "<p>Ah, 2020... What a miserable year you were. Well, being locked down for months with the family was tough, but during that time, I wound up starting a little \"COVID project\" that turned out to be something special.</p>\
    <p>Over the years, I'd always thought about making my own album, but never really had the inspiration to do it. In the effort to pass the time during the pandemic, I decided to \"just do it\" and start recording whatever came to mind at the moment.  The result was my new music project, The Beta Release.</p>\
    <p>I was able to get 4 songs recorded before life kicked in again, and this - an instrumental called <em>The Release</em> - is the first one that's ready to share.  The other 3 are mostly hard rock remakes of old electro-pop songs from the 80s/90s, but since I'm not really a vocalist, I'm working on bringing in someone else to handle that. Hopefully I'll be able to share those soon as well.</p>\
    <p>I hope that life will allow me to continue this project into the future.  I have a many more ideas for song remakes.  We'll see if they ever make it out of my head.</p>",
  },
  {
    id: 'vale',
    title: 'Vale Counseling',
    client: 'Vale Counseling',
    year: '2017',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/vale-logo.png',
    screenshot: '/images/work/screenshots/vale-screenshot.jpg',
    url: 'http://valecounseling.com',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes:
      "<p>This was kind of a fun \"passion project\" for my wife's former counseling practice. It's several years old now, but it's still a favorite of mine, and still serves the practice well.</p>\
    <p>I handled everything from design to development - even helping them with a new logo - and it's got a super nice, fully custom CMS, built with CraftCMS. I'm really proud of this one.</p>",
  },
  {
    id: 'adopted',
    title: 'AdoptED',
    client: 'Gladney Center for Adoption',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/adopted-logo.png',
    screenshot: '/images/work/screenshots/adopted-screenshot.jpg',
    url: '',
    media: '/images/work/video/adopted-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML/CSS/JS', 'ExpressionEngine'],
    notes:
      "<p>One of the big clients we had when I was working at Switch was the Gladney Center for Adoption. <strong>AdoptED</strong> was a program of theirs dedicated to promoting adoption through education. We were able to have a little fun with the design of this site, and push the boundaries a bit with the layout and interface. I love its look and feel, and had a lot of fun developing it.\
      <p>It was built using ExpressionEngine, which at the time was one of the best CMS platforms around. It also featured big, bold, fullscreen images and aggressive colors, along with some slick parallaxing that was all the rage at the time. I still think it's pretty cool.<p>\
      <p>Sadly, it no longer exists, so the best I can do is show you a walkthrough video. #WompWomp</p>",
  },
  {
    id: 'tots-nuggs',
    title: 'Tots & Nuggs',
    client: 'Boots',
    year: '2022',
    projectType: 'Song',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/totsandnuggs-screenshot.jpg',
    url: '',
    media:
      'https://soundcloud.com/the-beta-release/tots-nugs?si=ac1f0deed53e4c989695d00be8cad362&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    mediaType: 'audio',
    skills: ['Writing/Arranging/Production', 'Vocals', 'Bass Guitar', 'Guitar', 'Drum Programming'],
    notes: 'Notes will go here.',
  },
  {
    id: 'maridoe',
    title: 'Maridoe Golf Club',
    client: 'Maridoe Golf Club',
    year: '2017',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/maridoe-logo.png',
    screenshot: '/images/work/screenshots/maridoe-screenshot.jpg',
    url: 'https://maridoe.com/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'criquet',
    title: 'Criquet Shirts',
    client: 'Criquet Shirts',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/criquet-logo.png',
    screenshot: '/images/work/screenshots/criquet-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'Shopify'],
    notes: 'Notes will go here.',
  },
  {
    id: 'the-laurel',
    title: 'The Laurel',
    client: 'The Laurel Texas',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/thelaurel-logo.png',
    screenshot: '/images/work/screenshots/thelaurel-screenshot.jpg',
    url: '',
    media: '/images/work/video/thelaurel-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'the-interrogation',
    title: 'The Interrogation',
    client: 'Boots',
    year: '2022',
    projectType: 'Video',
    category: 'misc',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/theinterrogation-screenshot.jpg',
    url: '',
    media: 'https://youtu.be/lhPjK90urgk',
    mediaType: 'video',
    skills: ['Screenplay/Direction/Cinematography', 'Video Editing', 'Acting?'],
    notes: 'Notes will go here.',
  },
  {
    id: 'jordan',
    title: 'Jordan Tourism Board',
    client: 'Jordan Tourism Board North America',
    year: '2005',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/jordan-logo.png',
    screenshot: '/images/work/screenshots/jordan-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'Flash Programming', 'Website Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'electrico',
    title: 'The Electric Co',
    client: 'Passing Strangers',
    year: '2007',
    projectType: 'Music Video',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/electrico-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=CWyxoTYKXnw',
    mediaType: 'video',
    skills: ['Bass Guitar', 'Video Production'],
    notes: 'Notes will go here.',
  },
  {
    id: 'gladney',
    title: 'Gladney Center',
    client: 'Gladney Center for Adoption',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/gladney-logo.png',
    screenshot: '/images/work/screenshots/gladney-screenshot.jpg',
    url: 'https://adoptionsbygladney.com/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'dock-bass-solo',
    title: 'Bass Solo @ The Dock',
    client: 'Passing Strangers',
    year: '1998',
    projectType: 'Music Video',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/basssolodock-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=Bys69-mxu6E',
    mediaType: 'video',
    skills: ['Bass Guitar'],
    notes: 'Notes will go here.',
  },
  {
    id: 'falchi',
    title: 'The Falchi Building',
    client: 'Jametown Urban Management',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/falchi-logo.png',
    screenshot: '/images/work/screenshots/falchi-screenshot.jpg',
    url: '',
    media: '/images/work/video/falchi-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'birds-of-play',
    title: 'Birds of Play',
    client: 'Birds of Play FC',
    year: '2017',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/birdsofplay-logo.png',
    screenshot: '/images/work/screenshots/birdsofplay-screenshot.jpg',
    url: 'http://birdsofplay.boots.media/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'bluebird',
    title: 'Bluebird Real Estate',
    client: 'Bluebird Real Estate',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/bluebird-logo.png',
    screenshot: '/images/work/screenshots/bluebird-screenshot.jpg',
    url: 'https://bbre1.com/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'hinge',
    title: 'Hinge Analytics',
    client: 'Hinge Analytics',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/hinge-logo.png',
    screenshot: '/images/work/screenshots/hinge-screenshot.jpg',
    url: '',
    media: '/images/work/video/hinge-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML/CSS/JS', 'ExpressionEngine'],
    notes: 'Notes will go here.',
  },
  {
    id: 'see-you-today',
    title: 'See You Today',
    client: 'Interface',
    year: '1990',
    projectType: 'Music Video',
    category: 'music',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/seeyoutoday-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=trqFaoDmofs',
    mediaType: 'video',
    skills: ['Bass Guitar'],
    notes: 'Notes will go here.',
  },
  {
    id: 'dallas-guitar-repair',
    title: 'Dallas Guitar Repair',
    client: 'Dallas Guitar Repair',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/dallasguitarrepair-logo.png',
    screenshot: '/images/work/screenshots/dallasguitarrepair-screenshot.jpg',
    url: 'http://dallasguitarrepair.boots.media/',
    media: '',
    mediaType: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'possumkingdom',
    title: 'Possum Kingdom',
    client: 'Passing Strangers',
    year: '2007',
    projectType: 'Music Video',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/possumkingdom-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=A6r5pVIeptA',
    mediaType: 'video',
    skills: ['Bass Guitar', 'Video Production'],
    notes: 'Notes will go here.',
  },
  {
    id: 'pregnancy-hotline',
    title: 'Pregnancy Hotline',
    client: 'Gladney Center for Adoption',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/gladney-logo.png',
    screenshot: '/images/work/screenshots/pregnancyhotline-screenshot.jpg',
    url: '',
    media: '/images/work/video/pregnancyhotline-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML/CSS/JS', 'ExpressionEngine'],
    notes: 'Notes will go here.',
  },
  {
    id: 'new-years-day',
    title: 'New Years Day',
    client: 'Blood Red Sky',
    year: '2006',
    projectType: 'Music Video',
    category: 'music',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo.png',
    screenshot: '/images/work/screenshots/newyearsday-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=0w_aBtBo7PI',
    mediaType: 'video',
    skills: ['Bass Guitar', 'Video Production'],
    notes: 'Notes will go here.',
  },
  {
    id: 'doubler',
    title: 'Double R',
    client: 'Double R Brand by Ravi Ratan',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/doubler-logo.png',
    screenshot: '/images/work/screenshots/doubler-screenshot.jpg',
    url: '',
    media: '/images/work/video/doubler-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML/CSS/JS', 'Liquid', 'Shopify'],
    notes: 'Notes will go here.',
  },
]
