export const sections = [
  {
    id: 'all',
    label: 'All Projects',
    description: '',
  },
  {
    id: 'web-dev',
    label: 'Web Development',
    description:
      'Here are some of my more recent projects. Unfortunately, the web is an ever-evolving beast, so many of these either no longer exist, or have been redeveloped since I launched them. Archived links *might* be available upon request.',
  },
  {
    id: 'music',
    label: 'Music',
    description:
      'In fourth grade, music grabbed me by the ear and never let go. Until I discovered web development, it was my primary passion. Here are a few of the highlights over the years.',
  },
  {
    id: 'photo',
    label: 'Photography',
    description:
      "Along the way, I wound up picking up a camera and found that I kinda liked shooting photos as well. It's never really been a *passion* per se, but it's fun when I have the time.  Enjoy!",
  },
  {
    id: 'misc',
    label: 'Other Stuff',
    description: "Here are some other random things I've done.",
  },
]

export const projects = [
  {
    id: 'mizzen',
    title: 'Mizzen+Main Website',
    client: 'Mizzen+Main',
    year: '2016-2023',
    category: 'web-dev',
    agency: 'Mizzen+Main',
    logo: '/images/work/logos/mizzen-logo.png',
    screenshot: '/images/work/screenshots/mizzen-screenshot.jpg',
    url: '',
    media: '/images/work/video/mizzen-walkthrough.mp4',
    skills: ['HTML/CSS/JS', 'Next.js/React', 'Liquid', 'Site Management'],
    notes: 'Notes will go here.',
  },
  {
    id: 'the-release',
    title: 'The Release',
    client: 'The Beta Release (Me)',
    year: '2021',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/thebetarelease-logo.png',
    screenshot: '/images/work/screenshots/thebetarelease-screenshot.jpg',
    url: 'https://thebetarelease.com',
    media:
      'https://soundcloud.com/the-beta-release/the-release?in=the-beta-release/sets/first-four-demo/s-GJmPNOdFLgZ&si=3532862927724aefafb5105e8ec32838&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    skills: ['Writing/Arranging/Production', 'Bass Guitar', 'Guitar', 'Synths', 'Drum Programming'],
    notes: 'Notes will go here.',
  },
  {
    id: 'vale',
    title: 'Vale Counseling Website',
    client: 'Vale Counseling',
    year: '2017',
    category: 'web-dev',
    agency: 'Me',
    logo: '/images/work/logos/vale-logo.png',
    screenshot: '/images/work/screenshots/vale-screenshot.jpg',
    url: 'http://valecounseling.com',
    media: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'adopted',
    title: 'AdoptED Website',
    client: 'Gladney Center for Adoption',
    year: '2015',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/adopted-logo.png',
    screenshot: '/images/work/screenshots/adopted-screenshot.jpg',
    url: '',
    media: '',
    skills: ['HTML/CSS/JS', 'ExpressionEngine'],
    notes: 'Notes will go here.',
  },
  {
    id: 'criquet',
    title: 'Criquet Shirts Website',
    client: 'Criquet Shirts',
    year: '2018',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/criquet-logo.png',
    screenshot: '/images/work/screenshots/criquet-screenshot.jpg',
    url: '',
    media: '',
    skills: ['HTML/CSS/JS', 'Shopify'],
    notes: 'Notes will go here.',
  },
  {
    id: 'the-interrogation',
    title: 'The Interrogation',
    client: 'Me',
    year: '2022',
    category: 'misc',
    agency: 'Me',
    logo: '/images/work/logos/video-logo.png',
    screenshot: '/images/work/screenshots/theinterrogation-screenshot.jpg',
    url: '',
    media: 'https://youtu.be/lhPjK90urgk',
    skills: ['Screenplay/Direction/Cinematography', 'Video Editing', 'Acting?'],
    notes: 'Notes will go here.',
  },
  {
    id: 'jordan',
    title: 'Jordan Tourism Board Website',
    client: 'Jordan Tourism Board North America',
    year: '2005',
    category: 'web-dev',
    agency: 'Me',
    logo: '/images/work/logos/jordan-logo.png',
    screenshot: '/images/work/screenshots/jordan-screenshot.jpg',
    url: '',
    media: '',
    skills: ['HTML/CSS/JS', 'Website Design'],
    notes: 'Notes will go here.',
  },
  {
    id: 'the-laurel',
    title: 'The Laurel Website',
    client: 'The Laurel Texas',
    year: '2016',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/thelaurel-logo.png',
    screenshot: '/images/work/screenshots/thelaurel-screenshot.jpg',
    url: '',
    media: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'gladney',
    title: 'Gladney Center Website',
    client: 'Gladney Center for Adoption',
    year: '2018',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/gladney-logo.png',
    screenshot: '/images/work/screenshots/gladney-screenshot.jpg',
    url: 'https://adoptionsbygladney.com/',
    media: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'falchi',
    title: 'The Falchi Building Website',
    client: 'Jametown Urban Management',
    year: '2016',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/falchi-logo.png',
    screenshot: '/images/work/screenshots/falchi-screenshot.jpg',
    url: '',
    media: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'birds-of-play',
    title: 'Birds of Play Website',
    client: 'Birds of Play FC',
    year: '2017',
    category: 'web-dev',
    agency: 'Me',
    logo: '/images/work/logos/birdsofplay-logo.png',
    screenshot: '/images/work/screenshots/birdsofplay-screenshot.jpg',
    url: 'http://birdsofplay.boots.media/',
    media: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'bluebird',
    title: 'Bluebird Real Estate Website',
    client: 'Bluebird Real Estate',
    year: '2018',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/bluebird-logo.png',
    screenshot: '/images/work/screenshots/bluebird-screenshot.jpg',
    url: 'https://bbre1.com/',
    media: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'dallas-guitar-repair',
    title: 'Dallas Guitar Repair Website',
    client: 'Dallas Guitar Repair',
    year: '2016',
    category: 'web-dev',
    agency: 'Me',
    logo: '/images/work/logos/dallasguitarrepair-logo.png',
    screenshot: '/images/work/screenshots/dallasguitarrepair-screenshot.jpg',
    url: 'http://dallasguitarrepair.boots.media/',
    media: '',
    skills: ['HTML/CSS/JS', 'CraftCMS', 'Twig'],
    notes: 'Notes will go here.',
  },
  {
    id: 'pregnancy-hotline',
    title: 'Pregnancy Hotline Website',
    client: 'Gladney Center for Adoption',
    year: '2015',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/gladney-logo.png',
    screenshot: '/images/work/screenshots/pregnancyhotline-screenshot.jpg',
    url: '',
    media: '',
    skills: ['HTML/CSS/JS', 'ExpressionEngine'],
    notes: 'Notes will go here.',
  },
  {
    id: 'doubler',
    title: 'Double R Website',
    client: 'Double R Brand by Ravi Ratan',
    year: '2015',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/doubler-logo.png',
    screenshot: '/images/work/screenshots/doubler-screenshot.jpg',
    url: '',
    media: '',
    skills: ['HTML/CSS/JS', 'Shopify'],
    notes: 'Notes will go here.',
  },
]
